// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models
{
    public partial class Post
    {
        public int LatestPostQuoteId { get; set; }
        public DateTime PostDateTime { get; set; }
        public string Picture { get; set; }
    }
}